apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbpersonflatefs
  namespace: {{namespace}}
  cluster: dev-fss
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarbpersonflatefs/veilarbpersonflatefs:{{version}}
  port: 8080
  liveness:
    path: veilarbpersonflatefs/internal/isAlive
    initialDelay: 20
  readiness:
    path: veilarbpersonflatefs/internal/selftest
    initialDelay: 20
  prometheus:
    enabled: true
    path: veilarbpersonflatefs/internal/metrics
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: "3"
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  ingresses:
    - https://veilarbpersonflatefs-{{namespace}}.nais.adeo.no
    - https://app-{{namespace}}.adeo.no/veilarbpersonflatefs
  vault:
    enabled: true
  env:
    - ISSO_JWKS_URL
    - ISSO_HOST_URL
    - ISSO_ISSUER_URL
    - ISSO_ISALIVE_URL
    - VEILARBLOGIN_REDIRECT_URL_URL
    - VEILARBLOGIN_REDIRECT_URL_DESCRIPTION
    - OIDC_REDIRECT_URL
    - APPDYNAMICS_CONTROLLER_HOST_NAME
    - APPDYNAMICS_AGENT_ACCOUNT_NAME
    - APPDYNAMICS_CONTROLLER_PORT
    - APPDYNAMICS_CONTROLLER_SSL_ENABLED
