apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbpersonflatefs
  namespace: pto
  labels:
    team: pto
spec:
  image: docker.pkg.github.com/navikt/veilarbpersonflatefs/veilarbpersonflatefs:{{version}}
  port: 8080
  webproxy: true
  liveness:
    path: veilarbpersonflatefs/internal/isAlive
    initialDelay: 5
  readiness:
    path: veilarbpersonflatefs/internal/isReady
    initialDelay: 5
  prometheus:
    enabled: true
    path: veilarbpersonflatefs/internal/prometheus
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "2"
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  ingresses:
    - https://app.adeo.no/veilarbpersonflatefs
  vault:
    enabled: true
  envFrom:
    - configmap: pto-config
