apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbpersonflate
  namespace: poao
  labels:
    team: poao
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
spec:
  image: europe-north1-docker.pkg.dev/nais-management-233d/poao/poao-frontend:2024.01.11-15.42-89509d3
  port: 8080
  ingresses:
    - https://veilarbpersonflate.intern.dev.nav.no
  liveness:
    path: /internal/alive
    initialDelay: 10
  readiness:
    path: /internal/ready
    initialDelay: 10
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      allowAllUsers: true #todo burde vi legge inn noen roller her?
    sidecar:
      enabled: true
      autoLogin: true
  gcp:
    buckets:
      - name: poao-veilarbpersonflate-dev
        cascadingDelete: false
  accessPolicy:
    outbound:
      rules:
        - application: mulighetsrommet-api
          namespace: team-mulighetsrommet
        - application: obo-unleash
          namespace: obo
        - application: please
          namespace: dab
        - application: orkivar
          namespace: dab
        - application: veilarblest
          namespace: dab
        - application: amt-deltaker-bff
          namespace: amt
      external:
        - host: veilarbdialog.dev-fss-pub.nais.io
        - host: veilarbaktivitet.dev-fss-pub.nais.io
        - host: veilarbmalverk.dev-fss-pub.nais.io
        - host: veilarbperson.dev-fss-pub.nais.io
        - host: veilarboppfolging.dev-fss-pub.nais.io
        - host: veilarbportefolje.dev-fss-pub.nais.io
        - host: modiacontextholder-q1.dev-fss-pub.nais.io
        - host: veilarbveileder.dev-fss-pub.nais.io
        - host: veilarbvedtaksstotte.dev-fss-pub.nais.io
        - host: veilarboppgave.dev-fss-pub.nais.io
        - host: veilarbfilter.dev-fss-pub.nais.io
  env:
    - name: JSON_CONFIG
      value: >
        {
          "enableSecureLogs": true,
          "fallbackStrategy": "SERVE_INDEX_HTML",
          "auth": {
            "loginProvider": "AZURE_AD"
          },
          "gcs": {
            "bucketName": "poao-veilarbpersonflate-dev"
          },
          "enableModiaContextUpdater": {
            "url": "https://modiacontextholder-q1.dev-fss-pub.nais.io/modiacontextholder",
            "scope": "api://dev-fss.personoversikt.modiacontextholder-q1/.default"
          },
          "header": {
            "csp": {
              "connectSrc": ["'self'", "wss:", "*.nav.no", "*.adeo.no", "cdn.sanity.io", "storage.googleapis.com"],
              "frameSrc": ["vars.hotjar.com", "video.qbrick.com"],
              "imgSrc": ["'self'", "data:", "*.nav.no", "*.adeo.no", "cdn.sanity.io"]
            }
          },
          "redirects": [
            {
              "fromPath": "/internarbeidsflatedecorator/*",
              "toUrl": "https://internarbeidsflatedecorator-q1.intern.dev.nav.no",
              "preserveFromPath": true
            },
            {
              "fromPath": "/veilarbportefoljeflatefs/*",
              "toUrl": "https://veilarbportefoljeflate.intern.dev.nav.no",
              "preserveFromPath": false
            }
          ],
          "proxies": [
            {
              "fromPath": "/veilarbmalverk",
              "toUrl": "https://veilarbmalverk.dev-fss-pub.nais.io",
              "preserveFromPath": true
            },
            {
              "fromPath": "/veilarbperson",
              "toUrl": "https://veilarbperson.dev-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarbperson",
                "namespace": "pto",
                "cluster": "dev-fss"
              }
            },
            {
              "fromPath": "/veilarboppfolging",
              "toUrl": "https://veilarboppfolging.dev-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarboppfolging",
                "namespace": "pto",
                "cluster": "dev-fss"
              }
            },
            {
              "fromPath": "/veilarbdialog",
              "toUrl": "https://veilarbdialog.dev-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarbdialog",
                "namespace": "pto",
                "cluster": "dev-fss"
              }
            },
            {
              "fromPath": "/veilarbaktivitet",
              "toUrl": "https://veilarbaktivitet.dev-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarbaktivitet",
                "namespace": "pto",
                "cluster": "dev-fss"
              }
            },
            {
              "fromPath": "/veilarblest",
              "toUrl": "http://veilarblest.dab.svc.cluster.local",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarblest",
                "namespace": "dab",
                "cluster": "dev-gcp"
              }
            },
            {
              "fromPath": "/veilarbportefolje",
              "toUrl": "https://veilarbportefolje.dev-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarbportefolje",
                "namespace": "pto",
                "cluster": "dev-fss"
              }
            },
            {
              "fromPath": "/obo-unleash",
              "toUrl": "http://obo-unleash.obo.svc.cluster.local",
              "preserveFromPath": false,
               "toApp": {
                "name": "obo-unleash",
                "namespace": "obo",
                "cluster": "dev-gcp"
              }
            },
            {
              "fromPath": "/modiacontextholder",
              "toUrl": "https://modiacontextholder-q1.dev-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "modiacontextholder-q1",
                "namespace": "personoversikt",
                "cluster": "dev-fss"
              }
            },
            {
              "fromPath": "/veilarbveileder",
              "toUrl": "https://veilarbveileder.dev-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarbveileder",
                "namespace": "pto",
                "cluster": "dev-fss"
              }
            },
            {
              "fromPath": "/veilarbvedtaksstotte",
              "toUrl": "https://veilarbvedtaksstotte.dev-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarbvedtaksstotte",
                "namespace": "pto",
                "cluster": "dev-fss"
              }
            },
            {
              "fromPath": "/mulighetsrommet-api",
              "toUrl": "http://mulighetsrommet-api.team-mulighetsrommet",
              "preserveFromPath": false,
              "toApp": {
                "name": "mulighetsrommet-api",
                "namespace": "team-mulighetsrommet",
                "cluster": "dev-gcp"
              }
            },
            {
              "fromPath": "/veilarboppgave",
              "toUrl": "https://veilarboppgave.dev-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarboppgave",
                "namespace": "pto",
                "cluster": "dev-fss"
              }
            },
            {
              "fromPath": "/please",
              "toUrl": "http://please.dab",
              "preserveFromPath": false,
              "toApp": {
                "name": "please",
                "namespace": "dab",
                "cluster": "dev-gcp"
              }
            },
            {
              "fromPath": "/orkivar",
              "toUrl": "http://orkivar.dab",
              "preserveFromPath": false,
              "toApp": {
                "name": "orkivar",
                "namespace": "dab",
                "cluster": "dev-gcp"
              }
            },
            {
              "fromPath": "/veilarbfilter",
              "toUrl": "https://veilarbfilter.dev-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarbfilter",
                "namespace": "pto",
                "cluster": "dev-fss"
              }
            },
            {
              "fromPath": "/amt-deltaker-bff",
              "preserveFromPath": false,
              "toUrl": "http://amt-deltaker-bff.amt",
              "toApp": {
                "name": "amt-deltaker-bff",
                "namespace": "amt",
                "cluster": "dev-gcp"
              }
            }
          ]
        }
