apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbpersonflate
  namespace: poao
  labels:
    team: poao
  annotations:
    wonderwall.nais.io/beta: "true"
spec:
  image: ghcr.io/navikt/poao-frontend/poao-frontend:2023.01.13_08.09-36c09678654f
  port: 8080
  ingresses:
    - https://veilarbpersonflate.intern.dev.nav.no
  liveness:
    path: /internal/alive
    initialDelay: 10
  readiness:
    path: /internal/ready
    initialDelay: 10
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "1"
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      allowAllUsers: true #todo burde vi legge inn noen roller her?
    sidecar:
      enabled: true
      autoLogin: true
  gcp:
    buckets:
      - name: poao-veilarbpersonflate-dev
        cascadingDelete: false
  accessPolicy:
    outbound:
      rules:
        - application: poao-unleash
        - application: mulighetsrommet-api
          namespace: team-mulighetsrommet
      external:
        - host: veilarbdialog.dev-fss-pub.nais.io
        - host: veilarbaktivitet.dev-fss-pub.nais.io
        - host: veilarblest.dev-fss-pub.nais.io
        - host: veilarbmalverk.dev-fss-pub.nais.io
        - host: veilarbperson.dev-fss-pub.nais.io
        - host: veilarboppfolging.dev-fss-pub.nais.io
        - host: veilarbportefolje.dev-fss-pub.nais.io
        - host: modiacontextholder-q1.dev-fss-pub.nais.io
        - host: veilarbveileder.dev-fss-pub.nais.io
        - host: veilarbvedtaksstotte.dev-fss-pub.nais.io
        - host: veilarboppgave.dev-fss-pub.nais.io
  env:
    - name: JSON_CONFIG
      value: >
        {
          "enableSecureLogs": true,
          "fallbackStrategy": "SERVE_INDEX_HTML",
          "auth": {
            "loginProvider": "AZURE_AD"
          },
          "gcs": {
            "bucketName": "poao-veilarbpersonflate-dev"
          },
          "header": {
            "csp": {
              "connectSrc": ["'self'", "wss:", "*.nav.no", "*.adeo.no", "cdn.sanity.io", "storage.googleapis.com"],
              "frameSrc": ["vars.hotjar.com", "video.qbrick.com"]
            }
          },
          "redirects": [
            {
              "fromPath": "/internarbeidsflatedecorator/*",
              "toUrl": "https://internarbeidsflatedecorator-q1.intern.dev.nav.no",
              "preserveFromPath": true
            },
            {
              "fromPath": "/veilarbportefoljeflatefs/*",
              "toUrl": "https://veilarbportefoljeflate.intern.dev.nav.no",
              "preserveFromPath": false
            }
          ],
          "proxies": [
            {
              "fromPath": "/veilarbmalverk",
              "toUrl": "https://veilarbmalverk.dev-fss-pub.nais.io",
              "preserveFromPath": true
            },
            {
              "fromPath": "/veilarbperson",
              "toUrl": "https://veilarbperson.dev-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarbperson",
                "namespace": "pto",
                "cluster": "dev-fss"
              }
            },
            {
              "fromPath": "/veilarboppfolging",
              "toUrl": "https://veilarboppfolging.dev-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarboppfolging",
                "namespace": "pto",
                "cluster": "dev-fss"
              }
            },
            {
              "fromPath": "/veilarbdialog",
              "toUrl": "https://veilarbdialog.dev-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarbdialog",
                "namespace": "pto",
                "cluster": "dev-fss"
              }
            },
            {
              "fromPath": "/veilarbaktivitet",
              "toUrl": "https://veilarbaktivitet.dev-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarbaktivitet",
                "namespace": "pto",
                "cluster": "dev-fss"
              }
            },
            {
              "fromPath": "/veilarblest",
              "toUrl": "https://veilarblest.dev-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarblest",
                "namespace": "pto",
                "cluster": "dev-fss"
              }
            },
            {
              "fromPath": "/veilarbportefolje",
              "toUrl": "https://veilarbportefolje.dev-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarbportefolje",
                "namespace": "pto",
                "cluster": "dev-fss"
              }
            },
            {
              "fromPath": "/veilarbpersonflatefs",
              "toUrl": "http://poao-unleash.poao.svc.cluster.local",
              "preserveFromPath": false,
               "toApp": {
                "name": "poao-unleash",
                "namespace": "poao",
                "cluster": "dev-gcp"
              }
            },
            {
              "fromPath": "/modiacontextholder",
              "toUrl": "https://modiacontextholder-q1.dev-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "modiacontextholder-q1",
                "namespace": "personoversikt",
                "cluster": "dev-fss"
              }
            },
            {
              "fromPath": "/veilarbveileder",
              "toUrl": "https://veilarbveileder.dev-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarbveileder",
                "namespace": "pto",
                "cluster": "dev-fss"
              }
            },
            {
              "fromPath": "/veilarbvedtaksstotte",
              "toUrl": "https://veilarbvedtaksstotte.dev-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarbvedtaksstotte",
                "namespace": "pto",
                "cluster": "dev-fss"
              }
            },
            {
              "fromPath": "/mulighetsrommet-api",
              "toUrl": "http://mulighetsrommet-api.team-mulighetsrommet",
              "preserveFromPath": false,
              "toApp": {
                "name": "mulighetsrommet-api",
                "namespace": "team-mulighetsrommet",
                "cluster": "dev-gcp"
              }
            },
            {
              "fromPath": "/veilarboppgave",
              "toUrl": "https://veilarboppgave.dev-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarboppgave",
                "namespace": "pto",
                "cluster": "dev-fss"
              }
            }
          ]
        }
