apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: veilarbpersonflate
  namespace: poao
  labels:
    team: poao
spec:
  image: ghcr.io/navikt/poao-frontend/poao-frontend:2023.08.21_08.58-44493927cf80
  port: 8080
  ingresses:
    - https://veilarbpersonflate.intern.nav.no
  liveness:
    path: /internal/alive
    initialDelay: 10
  readiness:
    path: /internal/ready
    initialDelay: 10
  replicas:
    min: 2
    max: 6
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "2"
      memory: 1024Mi
    requests:
      cpu: 250m
      memory: 512Mi
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      allowAllUsers: true #todo burde vi legge inn noen roller her?
    sidecar:
      enabled: true
      autoLogin: true
  gcp:
    buckets:
      - name: poao-veilarbpersonflate-prod
        cascadingDelete: false
  accessPolicy:
    outbound:
      rules:
        - application: poao-unleash
        - application: mulighetsrommet-api
          namespace: team-mulighetsrommet
      external:
        - host: veilarbmalverk.prod-fss-pub.nais.io
        - host: veilarbperson.prod-fss-pub.nais.io
        - host: veilarboppfolging.prod-fss-pub.nais.io
        - host: veilarbdialog.prod-fss-pub.nais.io
        - host: veilarbportefolje.prod-fss-pub.nais.io
        - host: veilarbaktivitet.prod-fss-pub.nais.io
        - host: veilarblest.prod-fss-pub.nais.io
        - host: modiacontextholder.prod-fss-pub.nais.io
        - host: veilarbveileder.prod-fss-pub.nais.io
        - host: veilarbvedtaksstotte.prod-fss-pub.nais.io
        - host: veilarboppgave.prod-fss-pub.nais.io
        - host: veilarbfilter.prod-fss-pub.nais.io
  env:
    - name: JSON_CONFIG
      value: >
        {
          "enableSecureLogs": true,
          "fallbackStrategy": "SERVE_INDEX_HTML",
          "auth": {
            "loginProvider": "AZURE_AD"
          },
          "gcs": {
            "bucketName": "poao-veilarbpersonflate-prod"
          },
          "enableModiaContextUpdater": {
            "url": "https://modiacontextholder.prod-fss-pub.nais.io/modiacontextholder",
            "scope": "api://prod-fss.personoversikt.modiacontextholder/.default"
          },
          "header": {
            "csp": {
              "connectSrc": ["'self'", "wss:", "*.nav.no", "*.adeo.no", "cdn.sanity.io", "storage.googleapis.com"],
              "frameSrc": ["vars.hotjar.com", "video.qbrick.com"]
            }
          },
          "redirects": [
            {
              "fromPath": "/internarbeidsflatedecorator/*",
              "toUrl": "https://internarbeidsflatedecorator.intern.nav.no",
              "preserveFromPath": true
            },
            {
              "fromPath": "/veilarbportefoljeflatefs/*",
              "toUrl": "https://veilarbportefoljeflate.intern.nav.no",
              "preserveFromPath": false
            }
          ],
          "proxies": [
            {
              "fromPath": "/veilarbmalverk",
              "toUrl": "https://veilarbmalverk.prod-fss-pub.nais.io",
              "preserveFromPath": true
            },
            {
              "fromPath": "/veilarbperson",
              "toUrl": "https://veilarbperson.prod-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarbperson",
                "namespace": "pto",
                "cluster": "prod-fss"
              }
            },
            {
              "fromPath": "/veilarboppfolging",
              "toUrl": "https://veilarboppfolging.prod-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarboppfolging",
                "namespace": "pto",
                "cluster": "prod-fss"
              }
            },
            {
              "fromPath": "/veilarbdialog",
              "toUrl": "https://veilarbdialog.prod-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarbdialog",
                "namespace": "pto",
                "cluster": "prod-fss"
              }
            },
            {
              "fromPath": "/veilarbportefolje",
              "toUrl": "https://veilarbportefolje.prod-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarbportefolje",
                "namespace": "pto",
                "cluster": "prod-fss"
              }
            },
            {
              "fromPath": "/veilarbaktivitet",
              "toUrl": "https://veilarbaktivitet.prod-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarbaktivitet",
                "namespace": "pto",
                "cluster": "prod-fss"
              }
            },
            {
              "fromPath": "/veilarblest",
              "toUrl": "https://veilarblest.prod-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarblest",
                "namespace": "pto",
                "cluster": "prod-fss"
              }
            },
            {
              "fromPath": "/veilarbpersonflatefs",
              "toUrl": "http://poao-unleash.poao.svc.cluster.local",
              "preserveFromPath": false,
               "toApp": {
                "name": "poao-unleash",
                "namespace": "poao",
                "cluster": "prod-gcp"
              }
            },
            {
              "fromPath": "/modiacontextholder",
              "toUrl": "https://modiacontextholder.prod-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "modiacontextholder",
                "namespace": "personoversikt",
                "cluster": "prod-fss"
              }
            },
            {
              "fromPath": "/veilarbveileder",
              "toUrl": "https://veilarbveileder.prod-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarbveileder",
                "namespace": "pto",
                "cluster": "prod-fss"
              }
            },
            {
              "fromPath": "/veilarbvedtaksstotte",
              "toUrl": "https://veilarbvedtaksstotte.prod-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarbvedtaksstotte",
                "namespace": "pto",
                "cluster": "prod-fss"
              }
            },
            {
              "fromPath": "/mulighetsrommet-api",
              "toUrl": "http://mulighetsrommet-api.team-mulighetsrommet",
              "preserveFromPath": false,
              "toApp": {
                "name": "mulighetsrommet-api",
                "namespace": "team-mulighetsrommet",
                "cluster": "prod-gcp"
              }
            },
            {
              "fromPath": "/veilarboppgave",
              "toUrl": "https://veilarboppgave.prod-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarboppgave",
                "namespace": "pto",
                "cluster": "prod-fss"
              }
            },
            {
              "fromPath": "/veilarbfilter",
              "toUrl": "https://veilarbfilter.prod-fss-pub.nais.io",
              "preserveFromPath": true,
              "toApp": {
                "name": "veilarbfilter",
                "namespace": "pto",
                "cluster": "prod-fss"
              }
          }
          ]
        }
