name: Deploy to prod
on:
  workflow_dispatch: # This workflow can be triggered manually from: https://github.com/navikt/veilarbpersonflatefs/actions/workflows/deploy-prod.yaml
  push:
    branches:
      - main
env:
  CI: true
  TZ: Europe/Amsterdam

jobs:
  deploy-prod:
    name: Deploy static files to prod
    uses: ./.github/workflows/deploy-static-files.yaml
    with:
      env: prod
    secrets:
      READER_TOKEN: ${{ secrets.READER_TOKEN }}
      GCS_SA_KEY: ${{ secrets.GCS_SA_KEY_PROD }}
