name: paoa frontend container dev

on:
  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/poao-frontend-container-dev.yml'
      - '.nais/poao-nais-dev.yaml'
  workflow_dispatch:

concurrency:
  group: pto_frontend_container_dev
  cancel-in-progress: true

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: deploy gcp dev
        uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb # v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/poao-nais-dev.yaml
