name: Sjekk PR-kode

on: pull_request

jobs:
  build-application:
    name: Build application
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      id-token: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86
      - name: Setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # actions/setup-node@v7
        with:
          node-version: 24
          cache: 'pnpm'
          registry-url: "https://npm.pkg.github.com"
      - name: Install dependencies
        run: pnpm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Run tests
        run: pnpm run test
      - name: Build application
        run: pnpm run build
